https://huggingface.co/transformers/

pip install transformers

In [1]:
import tensorflow as tf
# Hack pro GPU na Windows
for gpu in tf.config.experimental.list_physical_devices('GPU'):
    tf.config.experimental.set_memory_growth(gpu, True)

In [18]:
from transformers import TFGPT2LMHeadModel

model = TFGPT2LMHeadModel.from_pretrained("gpt2")

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/498M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at gpt2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [19]:
from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [26]:
prompt_text = "In machine learning, support-vector machines are supervised learning models"
encoded_prompt = tokenizer.encode(prompt_text,
                                  add_special_tokens=False,
                                  return_tensors="tf")
encoded_prompt

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=
array([[  818,  4572,  4673,    11,  1104,    12, 31364,  8217,   389,
        28679,  4673,  4981]])>

In [29]:
num_sequences = 5
length = 40

generated_sequences = model.generate(
    input_ids=encoded_prompt,
    do_sample=True,
    max_length=length + len(encoded_prompt[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    repetition_penalty=1.0,
    num_return_sequences=num_sequences,
)

generated_sequences

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence


<tf.Tensor: shape=(5, 52), dtype=int32, numpy=
array([[  818,  4572,  4673,    11,  1104,    12, 31364,  8217,   389,
        28679,  4673,  4981,   326,  6032,   423,   257,  3161,    72,
         1895,   284,   262,   900,   286,  2274,  1366,    13,  1114,
         1672,    11,   611,   356,   423,   257,  7885,   326,  3407,
          281, 18253,  1988,    11,   356,   460,  1607,   284,   760,
          262,  1988,   286,   262, 11188,  5408,   287],
       [  818,  4572,  4673,    11,  1104,    12, 31364,  8217,   389,
        28679,  4673,  4981,  1912,   319,   617, 10238, 16113,    11,
          617,  6087,   286,   262,  6678,   327,  3033,    11,   290,
          617,  1366,  3858,    13,  1119,  2148, 28679,  4673,   351,
        35582,  7587,   290,  3105,    11,   362,    12, 19577, 35847,
         1231,   262, 13357,   286, 35582,  7587,    13],
       [  818,  4572,  4673,    11,  1104,    12, 31364,  8217,   389,
        28679,  4673,  4981,  1912,   319,   262, 12531,

In [30]:
for sequence in generated_sequences:
    text = tokenizer.decode(sequence, clean_up_tokenization_spaces=True)
    print(text)
    print("-" * 80)

In machine learning, support-vector machines are supervised learning models that typically have a priori access to the set of recent data. For example, if we have a variable that includes an integer value, we can expect to know the value of the corresponding expression in
--------------------------------------------------------------------------------
In machine learning, support-vector machines are supervised learning models based on some underlying algorithms, some combination of the usual C features, and some data types. They provide supervised learning with sequential processing and slow, 2-dimensional lookup without the complexity of sequential processing.
--------------------------------------------------------------------------------
In machine learning, support-vector machines are supervised learning models based on the abstractions and models of program code embedded in the language. The model-based knowledge itself needs to be associative, but it also need not be thinking abo